FROM centos

RUN yum install wget -y
RUN wget https://github.com/istio/istio/releases/download/1.7.0/istio-1.7.0-linux-amd64.tar.gz 
RUN wget https://github.com/istio/istio/releases/download/1.7.0/istioctl-1.7.0-linux-amd64.tar.gz
